Write more variables into zlib.pc
rust-lang/libz-sys pull request #157
Opened 2023-09-12 13:19 UTC by sagudev

Added version, that is parsed from zlib.h and `includedir` and `libdir`

2023-09-12 13:58 UTC, Byron requested changes
Thanks for contributing.

Could you explain what the purpose of this change is? What's the benefit, what does it fix?
Thanks

2023-09-12 14:01 UTC, sagudev commented
Some C/C++ programs have configure scripts that check zlib versions. This PR just fills some of those placeholder so `zlib.pc` can be used by configure script.

2023-09-13 06:21 UTC, Byron requested changes
Thank you, I think more information shouldn't hurt.

I thought about this and have to consider it a backwards-incompatible change as this will crash hard if a header file provided by any system does not contain the desired information, information that previously wasn't provided.

To be save, please make the version optional. Thank you.

2023-09-13 06:21 UTC, Byron commented on build.rs
> +            .replace("@includedir@", "${prefix}/include")
Let's remove `includedir` and `libdir`, as these are generated and can as well be generated by the build system interpreting these files.

2023-09-13 06:44 UTC, sagudev commented
> I thought about this and have to consider it a backwards-incompatible change as this will crash hard if a header file provided by any system does not contain the desired information, information that previously wasn't provided.

Making zlib.pc is only done when compiling from source, which is part of this repo, so zlib.h will always contain that information, that's how zlib's build system is doing it. But better safe than sorry, so there will be no panic on version fail.

2023-09-13 07:43 UTC, Byron requested changes
I am sorry for the earlier review - it was based on a browser-only session with a tiny context window. This made me miss that indeed, this change only affects the vendored version, but also that comes with `zlib.pc.in` which has `libdir` and `includedir` variables ready for substitution.

With that knowledge, I think the change is good the way it was *before* 😅, assuming that you are sure that the generated `includedir` and `libdir` variables will be correct on any system.

Thanks for bearing with me.

2023-09-13 07:53 UTC, sagudev commented
No worries, git stores previous commits too.

2023-09-13 07:56 UTC, sagudev commented
> assuming that you are sure that the generated includedir and libdir variables will be correct on any system.

If prefix is valid than includedir and libdir should be valid too.

2023-09-13 08:51 UTC, merged

2023-09-13 08:52 UTC, Byron commented
Thanks again!