Do not check pkg-config when cross-compiling for android
rust-lang/libz-sys pull request #199
Opened 2024-07-26 14:38 UTC by sagudev

just moves `target.contains("android")` check before pkg-config check

2024-07-26 14:51 UTC, sagudev commented
CI has some network issues

2024-07-26 15:00 UTC, Byron requested changes
Could you provide a motivation for this change either as commit message, as in-code comment, or a combination of both?

Thank you!

2024-07-26 16:36 UTC, Byron commented
Could you spell out everything in the commit message, like I am 3 years old?
The current explanation doesn’t tell me much. Imagine someone who has no background in this.
Thanks again

2024-07-26 18:45 UTC, sagudev commented
In case commit message is unclear, you can also edit it yourself (I always `Allow edits by maintainers`).

2024-07-26 18:59 UTC, Byron commented
I really meant the 'please explain it like I am 3' because I wouldn't know how to improve it - it's entirely unclear to me, I have no context.

2024-07-26 19:50 UTC, sagudev commented
But it is ok now? (There was a force push between https://github.com/rust-lang/libz-sys/pull/199#issuecomment-2253110900 and https://github.com/rust-lang/libz-sys/pull/199#issuecomment-2253289469)

2024-07-27 04:59 UTC, Byron approved these changes
Thanks a lot, I understand what's going on now and can confirm that the change makes sense to accomplish this goal (without having tested or otherwise validated it).

2024-07-27 04:59 UTC, merged